### ISSUE TITLE
Bash debug not working with WSL2 and Remote VS Code

### ISSUE THREAD

**Issue by giggio** [rogalmic/vscode-bash-debug#137]
## Executables
Version of bash-debug: 0.3.7

Output of following commands:

```
❯ which bash
/bin/bash

❯ code --version
1.44.2
ff915844119ce9485abfe8aa9076ec76b5300ddd
x64

❯ bash -c 'uname -a; for P in bash bashdb cat mkfifo pkill; do echo ---; which -a $P; command $P --version; done'
Linux giggiosurfacepro5 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
---
/bin/bash
GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
---
bash: bashdb: command not found
---
/bin/cat
cat (GNU coreutils) 8.30
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Torbjorn Granlund and Richard M. Stallman.
---
/usr/bin/mkfifo
mkfifo (GNU coreutils) 8.30
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David MacKenzie.
---
/usr/bin/pkill
pkill from procps-ng UNKNOWN
```

## Debug output

This is from Log(Window):

````
[2020-04-27 21:28:22.127] [renderer3] [error] TypeError: Cannot read property 'on' of undefined
    at BashDebugSession.disconnectRequest (/home/giggio/.vscode-server/extensions/rogalmic.bash-debug-0.3.7/out/bashDebug.js:36:27)
    at BashDebugSession.dispatchRequest (/home/giggio/.vscode-server/extensions/rogalmic.bash-debug-0.3.7/node_modules/vscode-debugadapter/lib/debugSession.js:348:22)
    at BashDebugSession.dispatchRequest (/home/giggio/.vscode-server/extensions/rogalmic.bash-debug-0.3.7/node_modules/vscode-debugadapter/lib/loggingDebugSession.js:54:15)
    at BashDebugSession.handleMessage (/home/giggio/.vscode-server/extensions/rogalmic.bash-debug-0.3.7/node_modules/vscode-debugadapter/lib/protocol.js:60:18)
    at BashDebugSession._handleData (/home/giggio/.vscode-server/extensions/rogalmic.bash-debug-0.3.7/node_modules/vscode-debugadapter/lib/protocol.js:158:34)
    at Socket.<anonymous> (/home/giggio/.vscode-server/extensions/rogalmic.bash-debug-0.3.7/node_modules/vscode-debugadapter/lib/protocol.js:79:44)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10): Error: TypeError: Cannot read property 'on' of undefined
    at BashDebugSession.disconnectRequest (/home/giggio/.vscode-server/extensions/rogalmic.bash-debug-0.3.7/out/bashDebug.js:36:27)
    at BashDebugSession.dispatchRequest (/home/giggio/.vscode-server/extensions/rogalmic.bash-debug-0.3.7/node_modules/vscode-debugadapter/lib/debugSession.js:348:22)
    at BashDebugSession.dispatchRequest (/home/giggio/.vscode-server/extensions/rogalmic.bash-debug-0.3.7/node_modules/vscode-debugadapter/lib/loggingDebugSession.js:54:15)
    at BashDebugSession.handleMessage (/home/giggio/.vscode-server/extensions/rogalmic.bash-debug-0.3.7/node_modules/vscode-debugadapter/lib/protocol.js:60:18)
    at BashDebugSession._handleData (/home/giggio/.vscode-server/extensions/rogalmic.bash-debug-0.3.7/node_modules/vscode-debugadapter/lib/protocol.js:158:34)
    at Socket.<anonymous> (/home/giggio/.vscode-server/extensions/rogalmic.bash-debug-0.3.7/node_modules/vscode-debugadapter/lib/protocol.js:79:44)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at t.RawDebugSession.handleErrorResponse (file:///C:/Users/giovanni.LAMBDA3/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3044:67)
    at file:///C:/Users/giovanni.LAMBDA3/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3043:339
    at async t.RawDebugSession.shutdown (file:///C:/Users/giovanni.LAMBDA3/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3041:336)
````

## Details
This is the error:
![image](https://user-images.githubusercontent.com/334958/80433792-50e44880-88ce-11ea-8cbe-c9b2afb523c6.png)

````
Error: BUG: timeout while validating environment. If it is reproducible, please report it to https://github.com/rogalmic/vscode-bash-debug/issues.
````

**Comment by nsolthe** [comment]
I am using this extension in an Remote VS Code on a Linux mint 19.2 (Tina) and it works fine for me.

Version of bash-debug: 0.3.9
VS Code Version = 1.46.1
Linux Kernel = 4.15.0-106-generic

Have you tried again with the latest versions?

**Comment by giggio** [comment]
Just tried it now. Now I don't even get an error anymore, it just does not start the debug session.
It is not any remote, it is on WSL2.
